ballerina-platform/module-ballerina-websub

.github/workflows/daily-build.yml
=> Enable daily build

websub-ballerina/build.gradle
$subject
- Exclude `websub_advanced_integration_tests`
- Exclude `websub_generic_integration_tests`
=> Exclude unnecessary test packages

websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubConnectorListener.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/Hub.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/HubSubscriber.java
Fixes https://github.com/ballerina-platform/module-ballerina-websub/runs/856212608?check_suite_focus=true
Add empty values for strand names and metadata.
ballerina-platform/ballerina-lang#23683
=> Add null for strand name and metadata

websub-ballerina/build.gradle
=> Fix spelling issue

websub-ballerina/build.gradle
=> Remove tests skip from push configs

gradle.properties, websub-ballerina/build.gradle, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberConstants.java
$subject
- Upgrade ballerina lang version and module version
- Enable offline build temporary until this (https://github.com/ballerina-platform/ballerina-lang/issues/24975) issue got fixed.
=> Upgrade version and enable offline build

websub-ballerina/src/websub_generic_integration_tests/tests/integration-tests/subscriber/test_subscriber_startup.bal
$Subject
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Fix error which produced by the new parser

build.gradle, websub-ballerina/src/websub_advanced_integration_tests/tests/utils.bal, websub-ballerina/src/websub_generic_integration_tests/tests/utils.bal
=> Update Nexus URL and fix test utils

gradle.properties, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberConstants.java
=> Upgrade versions

build.gradle, websub-ballerina/src/websub/Module.md, websub-ballerina/src/websub/commons.bal, websub-ballerina/src/websub/hub_persistence.bal, websub-ballerina/src/websub/hub_service.bal, websub-ballerina/src/websub/natives.bal, websub-ballerina/src/websub/publisher_client.bal, websub-ballerina/src/websub/subscriber_client.bal, websub-ballerina/src/websub/subscriber_service_caller.bal, websub-ballerina/src/websub/subscriber_service_endpoint.bal, websub-ballerina/src/websub/tests/unit-tests/test_specific_subscriber.bal, websub-ballerina/src/websub_generic_integration_tests/tests/constants.bal, websub-ballerina/src/websub_generic_integration_tests/tests/integration-tests/subscriber/test_custom_subscribers.bal, websub-ballerina/src/websub_generic_integration_tests/tests/integration-tests/subscriber/test_subscriber.bal
$subject
https://github.com/ballerina-platform/ballerina-lang/pull/25637
- macOS
- Java 8
- SLP4
=> Add class support

websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubConnectorListener.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubEmptyCallableUnitCallback.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubHttpResource.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubHttpService.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubResourceDispatcher.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubServicesRegistry.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberConstants.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubUtils.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/Hub.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/HubSubscriber.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/HubNativeOperationHandler.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/PublisherNativeOperationHandler.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/SubscriberNativeOperationHandler.java
=> Migrate jBallerina Runtime APIs

.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, README.md, gradle/wrapper/gradle-wrapper.properties, websub-ballerina/Ballerina.toml, websub-ballerina/build.gradle, websub-ballerina/src/websub/commons.bal, websub-ballerina/src/websub/natives.bal, websub-ballerina/src/websub/subscriber_service_endpoint.bal, websub-ballerina/src/websub_advanced_integration_tests/tests/advanced_services/01_websub_publisher.bal, websub-ballerina/src/websub_advanced_integration_tests/tests/subscriber/test_subscribers_at_basic_auth_secured_hub.bal, websub-ballerina/src/websub_generic_integration_tests/tests/integration-tests/subscriber/test_custom_subscribers.bal, websub-ballerina/src/websub_generic_integration_tests/tests/integration-tests/subscriber/test_subscriber.bal, websub-native/build.gradle, websub-native/src/main/java/module-info.java, websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubConnectorListener.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubDispatcher.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubResourceDispatcher.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubUtils.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/Hub.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/HubSubscriber.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/HubNativeOperationHandler.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/SubscriberNativeOperationHandler.java
=> Migrate websub module to JDK 11

.github/workflows/build-master.yml
$subject
releated issue: https://github.com/ballerina-platform/module-ballerina-websub/issues/36
=> Skip tests from snapshot release

websub-ballerina/build.gradle, websub-ballerina/src/websub/hub_service.bal, websub-ballerina/src/websub/publisher_client.bal, websub-ballerina/src/websub/subscriber_client.bal, websub-ballerina/src/websub/subscriber_service_endpoint.bal, websub-ballerina/src/websub_generic_integration_tests/tests/integration-tests/subscriber/test_custom_subscribers.bal, websub-ballerina/src/websub_generic_integration_tests/tests/utils.bal, websub-native/src/main/java/module-info.java, websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubConnectorListener.java, websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubException.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubDispatcher.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubEmptyCallableUnitCallback.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubHttpResource.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubHttpService.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubResourceDispatcher.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubServicesRegistry.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberConstants.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubUtils.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/Hub.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/HubSubscriber.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/HubNativeOperationHandler.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/PublisherNativeOperationHandler.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/SubscriberNativeOperationHandler.java
$subject.
Fixed with: https://github.com/ballerina-platform/module-ballerina-websub/issues/38
=> Migrate Ballerina runtime APIs

.github/workflows/build-master.yml
=> Edit the gradle publish command

gradle.properties, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberConstants.java
=> Update Websub version and other stdlib versions

websub-native/build.gradle, websub-native/src/main/java/module-info.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java, websub-native/src/main/java/org/ballerinalang/net/websub/compiler/WebSubServiceCompilerPlugin.java
> $title
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Align with new Diagnostic API

.github/workflows/pull-request.yml
$subject.
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/569
=> Change tokens in PR build

websub-ballerina/src/websub/hub_service.bal, websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaConnectorException.java, websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubConnectorListener.java, websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubException.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubDispatcher.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubEmptyCallableUnitCallback.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubHttpResource.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubHttpService.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubResourceDispatcher.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubServicesRegistry.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberConstants.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubUtils.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/Hub.java, websub-native/src/main/java/org/ballerinalang/net/websub/hub/HubSubscriber.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/HubNativeOperationHandler.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/PublisherNativeOperationHandler.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/SubscriberNativeOperationHandler.java
=> Migrate WebSub module to new runtime APIs

websub-advanced-integration-tests/build.gradle, websub-ballerina/build.gradle, websub-generic-integration-tests/build.gradle
=> Enable copying of dependency caches and doc generation

websub-advanced-integration-tests/tests/test_subscribers_at_basic_auth_secured_hub.bal, websub-ballerina/Package.md, websub-ballerina/commons.bal, websub-ballerina/hub_service.bal, websub-ballerina/subscriber_client.bal, websub-ballerina/subscriber_service_endpoint.bal, websub-generic-integration-tests/tests/01_websub_publisher.bal, websub-generic-integration-tests/tests/02_redirection_publishers.bal, websub-generic-integration-tests/tests/test_subscriber_startup.bal
=> Update log API changes

websub-ballerina/subscriber_client.bal, websub-generic-integration-tests/tests/utils.bal
=> Fix union Type change

websub-advanced-integration-tests/tests/utils.bal, websub-ballerina/commons.bal, websub-ballerina/hub_service.bal, websub-ballerina/publisher_client.bal, websub-ballerina/subscriber_client.bal, websub-ballerina/subscriber_service_endpoint.bal, websub-generic-integration-tests/Ballerina.toml, websub-generic-integration-tests/tests/01_websub_publisher.bal, websub-generic-integration-tests/tests/test_subscriber.bal, websub-generic-integration-tests/tests/test_subscriber_startup.bal, websub-generic-integration-tests/tests/utils.bal, websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubConnectorListener.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubHttpResource.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubHttpService.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubUtils.java
=> Fix breaking Language API changes

build.gradle, gradle.properties, websub-advanced-integration-tests/Ballerina.toml, websub-advanced-integration-tests/build.gradle, websub-advanced-integration-tests/tests/test_subscribers_at_basic_auth_secured_hub.bal, websub-ballerina/Ballerina.toml, websub-ballerina/build.gradle, websub-generic-integration-tests/Ballerina.toml, websub-generic-integration-tests/build.gradle, websub-generic-integration-tests/tests/01_websub_publisher.bal, websub-generic-integration-tests/tests/test_different_content_type_subscribers.bal, websub-generic-integration-tests/tests/test_multiple_subscribers.bal, websub-generic-integration-tests/tests/test_subscriber.bal, websub-generic-integration-tests/tests/test_unsubscription_client.bal
=> Remove runtime stdlib dependency

websub-advanced-integration-tests/tests/test_subscribers_at_basic_auth_secured_hub.bal, websub-ballerina/tests/test_discovery_response_parsing.bal, websub-ballerina/tests/test_specific_subscriber.bal, websub-generic-integration-tests/tests/test_custom_subscribers.bal, websub-generic-integration-tests/tests/test_different_content_type_subscribers.bal, websub-generic-integration-tests/tests/test_multiple_subscribers.bal, websub-generic-integration-tests/tests/test_redirected_subscribers.bal, websub-generic-integration-tests/tests/test_subscriber.bal, websub-generic-integration-tests/tests/test_subscriber_startup.bal
=> Migrate testerina API change

websub-ballerina/build.gradle, websub-ballerina/subscriber_client.bal, websub-ballerina/subscriber_service_endpoint.bal
=> Migrate bal command change

websub-ballerina/subscriber_service_caller.bal
$subject in line with same change in http module in https://github.com/ballerina-platform/module-ballerina-http/pull/173
=> Remove status code related remote functions

build.gradle, gradle.properties, websub-ballerina/Ballerina.toml, websub-ballerina/build.gradle, websub-ballerina/commons.bal
> $title
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Remove config module dependency

websub-ballerina/subscriber_service_endpoint.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

websub-ballerina/commons.bal, websub-ballerina/errors.bal, websub-ballerina/tests/basic_subscriber_test.bal, websub-ballerina/websub_types.bal, websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubConnectorListener.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubEmptyCallableUnitCallback.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubResourceDispatcher.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberConstants.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java
$subject as per https://github.com/ballerina-platform/ballerina-standard-library/issues/786 part of https://github.com/ballerina-platform/ballerina-standard-library/issues/823
=> Update Subscriber service with swan lake design changes

websub-ballerina/Ballerina.toml, websub-ballerina/Dependencies.toml, websub-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
=> Add Dependencies.toml

websub-ballerina/build.gradle
> Improve build task to revert Dependencies toml
=> Improve build task to revert Dependencies toml

websub-ballerina/Package.md
=> Update the doc with new syntax

websub-ballerina/annotation.bal, websub-ballerina/subscriber_service_endpoint.bal, websub-ballerina/tests/basic_subscriber_test.bal, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubResourceDispatcher.java
> $subject
> Removing bugs in the previous release 
> Protocol compliance issue in subscription-intent verification (logic changed properly)
> Remove unwanted configurations from `websub:SubscriptionServiceConfiguration`.
=> WebSub required fixes for release

.github/workflows/build-master.yml, .github/workflows/pull-request.yml, websub-ballerina/build.gradle, websub-native/build.gradle, websub-native/src/main/java/org/ballerinalang/net/websub/BallerinaWebSubConnectorListener.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubResourceDispatcher.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberServiceValidator.java, websub-native/src/main/java/org/ballerinalang/net/websub/WebSubUtils.java, websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/SubscriberNativeOperationHandler.java
=> Update build-configurations to generate code-coverage report

README.md, websub-ballerina/Package.md
=> Update links and description in Readme.md and Package.md

websub-ballerina/request_processor.bal, websub-ballerina/utils.bal
=> Update crypto-hmac usage to support latest api-change

build.gradle
=> Add missing std-lib random dependency repository

build.gradle, websub-ballerina/build.gradle
=> Re-order Build Tasks to publish to Ballerina Central

.github/workflows/publish-release.yml, build.gradle, websub-ballerina/build.gradle
=> Republish artifacts to ballerina-central

.github/workflows/pull-request.yml
> Update Code Coverage report task in  pull_request.yml file.
=> Update codcov report generation task in PR Github Action

websub-ballerina/Package.md, websub-ballerina/build.gradle
=> Remove publishing testable jar and exec artifacts

websub-ballerina/annotation.bal, websub-ballerina/http_service.bal, websub-ballerina/sub_listener.bal, websub-ballerina/utils.bal
=> Migrate fixes in master to the latest release branch

README.md
=> Add Codecov Badge in README

websub-ballerina/build.gradle
Filter only package native classes and ballerina classes for test coverage report using includes flag.
Fixes ballerina-platform/ballerina-lang#28951
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> Add specific includes for code coverage

websub-ballerina/resource_discovery.bal, websub-ballerina/tests/additional_external_error_data_test.bal, websub-ballerina/tests/basic_subscriber_test.bal, websub-ballerina/tests/default_method_impl_test.bal, websub-ballerina/tests/multi_service_listener_test.bal, websub-ballerina/tests/ssl_enabled_subscriber_test.bal, websub-ballerina/tests/websub_config_manual_attach_test.bal
=> Update http-client usage according to latest api-change

websub-ballerina/Package.md
=> Update the package md according to curent API changes

websub-ballerina/sub_listener.bal, websub-ballerina/tests/websub_config_manual_attach_test.bal
=> Rename method to initialize websub-listener with configurations

gradle.properties, websub-ballerina/tests/optional_subscriber_target_test.bal, websub-ballerina/tests/service_path_generation_test.bal, websub-ballerina/tests/subscription_initiation_test.bal, websub-ballerina/tests/test_init.bal, websub-ballerina/utils.bal
=> Fix compilation errors

build.gradle, websub-ballerina/build.gradle
=> Strip stdlib dependency version

websub-compiler-plugin-test/build.gradle
=> Fix compiler plugin test failure

websub-compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/visitor/ListenerInitiationExpressionVisitor.java
=> Fix type validation issue with implicit new expressions

changelog.md, websub-compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/AnalyserUtils.java, websub-compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/ServiceAnalysisTask.java, websub-compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/validator/ServiceDeclarationValidator.java, websub-compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/visitor/ListenerInitiationExpressionVisitor.java
=> Refactor compiler plugin validation logic

websub-compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/visitor/ListenerInitiationExpressionVisitor.java
=> Fix listener init argument validation for explicit new expressions

.github/workflows/daily-build.yml
=> Fix character encoding issue in websub daily build

websub-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
=> Set flag to enable Jacoco Coverage XML generation

websub-ballerina/native.bal, websub-ballerina/request_processor.bal, websub-ballerina/tests/subscriber_with_error_return_types.bal
=> Fix logic issue in returning error types with subscriber service remote functions

websub-ballerina/resource_discovery.bal, websub-ballerina/subscriber_client.bal
=> Migrate latest http-client changes

build.gradle, gradle.properties, websub-ballerina/Ballerina.toml, websub-ballerina/build.gradle
> $subject
Related Issues [#1720](https://github.com/ballerina-platform/ballerina-distribution/issues/1720)
=> Remove Guava dependency from the module

websub-ballerina/errors.bal, websub-ballerina/sub_listener.bal, websub-ballerina/subscriber_client.bal, websub-ballerina/tests/subscription_initiation_test.bal, websub-ballerina/tests/subscription_redirect_test.bal
=> Fix compilation issues in dependency update

websub-ballerina/Module.md
=> Update Module md according to standards

websub-ballerina/resource_discovery.bal, websub-ballerina/subscriber_client.bal, websub-ballerina/tests/additional_external_error_data_test.bal, websub-ballerina/tests/basic_subscriber_test.bal, websub-ballerina/tests/multi_service_listener_test.bal, websub-ballerina/tests/ssl_enabled_subscriber_test.bal, websub-ballerina/tests/subscriber_with_error_return_types.bal, websub-ballerina/tests/websub_config_manual_attach_test.bal
> $subject
Related to [#423](https://github.com/ballerina-platform/module-ballerina-http/pull/423)
=> Sync with HTTP inbound error response update

websub-ballerina/errors.bal
=> Define ServiceExecutionError for service execution failures

gradle.properties
$subject. This ensures the package is published only to Github Packages and not to central.
=> [DO NOT MERGE] Bump ballerina gradle plugin

.github/workflows/build-timestamped-master.yml, .github/workflows/publish-release.yml
=> Update ballerina plugin version to 0.9.0

websub-ballerina/Package.md
> $subject
Part of [#1462](https://github.com/ballerina-platform/ballerina-standard-library/issues/1462)
=> Correct the Ballerina site link

websub-ballerina/Package.md
> $subject
Part of [#1462](https://github.com/ballerina-platform/ballerina-standard-library/issues/1462)
=> Update Package.md links into HTML format

compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/AnalyserUtils.java, compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/validator/ServiceDeclarationValidator.java, gradle.properties
=> Fix issues compiler plugin test failure

gradle.properties
Update dependency version to latest
=> Update dependency version to latest

.github/workflows/publish-release.yml, .gitignore, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/build.gradle, build-config/resources/Ballerina.toml, build-config/resources/CompilerPlugin.toml, gradle.properties
$Subject
Related Issue: [#1746](https://github.com/ballerina-platform/ballerina-standard-library/issues/1746)
=> Make the Ballerina Project Tooling Friendly

gradle.properties
=> Update Netty version

gradle.properties
=> Update Netty TC Native version

ballerina/Ballerina.toml, ballerina/Dependencies.toml, ballerina/sub_listener.bal
=> [FIX] Logic issue in unsubscription verification awaiting strategy

ballerina/Ballerina.toml, ballerina/Dependencies.toml
=> [FIX] Observer dependency version

ballerina/Ballerina.toml, docs/proposals/service-path-generation.md
> $subject
Related to [#2253](https://github.com/ballerina-platform/ballerina-standard-library/issues/2253)
=> Add compile-time unique service path generation proposal

docs/proposals/service-path-generation.md
=> Fix the formatting issue

.github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml
> $subject
Related to [#1849](https://github.com/ballerina-platform/ballerina-standard-library/issues/1849)
N/A
=> Fix trivy scan

ballerina/Dependencies.toml, ballerina/tests/isolated_subscriber_test.bal, native/src/main/java/io/ballerina/stdlib/websub/NativeHttpToWebsubAdaptor.java
> $subject
Related to [#2382](https://github.com/ballerina-platform/ballerina-standard-library/issues/2383)
N/A
=> Migrate to latests ballerina runtime APIs

.github/workflows/build-timestamped-master.yml
$Subject
Related: [#2362](https://github.com/ballerina-platform/ballerina-standard-library/issues/2362)
N/A
=> Skip Master Build for `.md` File Changes

ballerina/sub_listener.bal, gradle.properties
> $subject
Related to HTTP PR [#719](https://github.com/ballerina-platform/module-ballerina-http/pull/719)
N/A
~- [ ] Linked to an issue~
~- [ ] Updated the changelog~
~- [ ] Added tests~
=> Update `websub:Listener` to use latest APIs

ballerina/http_service.bal, ballerina/sub_listener.bal
> $subject
N/A
~- [ ] Linked to an issue~
~- [ ] Updated the changelog~
~- [ ] Added tests~
=> Move unsubscription initiation log to http-service

ballerina/http_service.bal, ballerina/tests/content_verification_test.bal, ballerina/tests/subscription_initiation_test.bal, ballerina/tests/subscription_redirect_test.bal, ballerina/tests/test_init.bal, ballerina/tests/unsubscription_test.bal, ballerina/tests/utils_test.bal, ballerina/utils.bal
> $subject
Fixes [#2392](https://github.com/ballerina-platform/ballerina-standard-library/issues/2392)
N/A
=> Fix compiler warnings

docs/proposals/service-path-generation.md
=> Fix formatting issues

native/src/main/java/io/ballerina/stdlib/websub/NativeHttpToWebsubAdaptor.java
> $subject
Related to [#2383](https://github.com/ballerina-platform/ballerina-standard-library/issues/2383)
N/A
=> Add check for service-object isolation

ballerina/subscriber_client.bal, ballerina/tests/additional_external_error_data_test.bal, ballerina/tests/basic_subscriber_test.bal, ballerina/tests/content_verification_test.bal, ballerina/tests/default_method_impl_test.bal, ballerina/tests/multi_service_listener_test.bal, ballerina/tests/optional_subscriber_target_test.bal, ballerina/tests/service_path_generation_test.bal, ballerina/tests/ssl_enabled_subscriber_test.bal, ballerina/tests/subscriber_with_error_return_types.bal, ballerina/tests/subscription_initiation_test.bal, ballerina/tests/subscription_redirect_test.bal, ballerina/tests/test_discovery_response_parsing.bal, ballerina/tests/test_init.bal, ballerina/tests/unsubscription_test.bal, ballerina/tests/utils_test.bal, ballerina/tests/websub_config_manual_attach_test.bal
> $subject
Related to [#2182](https://github.com/ballerina-platform/ballerina-standard-library/issues/2182)
N/A
=> Remove unwanted taint checks

gradle.properties
$Subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2396
N/A
=> Update gradle-plugin version

.github/workflows/publish-release.yml
=> Resolve merge conflicts

ballerina/build.gradle, build.gradle
> $subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2436
N/A
=> Fix ballerina publish not depending on compiler plugin tests

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
Related to - https://github.com/ballerina-platform/ballerina-standard-library/issues/2503
N/A
=> Upgrade the module and distribution versions

ballerina/tests/unsubscription_test.bal, gradle.properties
=> [FIX] Test case related to unsubscription flow

docs/spec/spec.md
> $subject
Fixes [#2162](https://github.com/ballerina-platform/ballerina-standard-library/issues/2161)
N/A
=> Add WebSub Spec

ballerina/commons.bal, ballerina/http_service.bal, ballerina/request_processor.bal, ballerina/resource_discovery.bal, ballerina/subscriber_client.bal, ballerina/subscriber_service.bal
=> Update API docs

docs/spec/spec.md
> $subject
Reference PR: https://github.com/ballerina-platform/module-ballerina-http/pull/873
N/A
=> Update the introduction of WebSub spec

docs/spec/spec.md
=> Add the URL link for issues

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/build.gradle, build-config/resources/Ballerina.toml
> $subject
N/A
- ~[ ] Linked to an issue~
- ~[ ] Updated the changelog~
- ~[ ] Added tests~
- ~[ ] Updated the spec~
=> Update to 2201.0.1 patch distribution

ballerina/subscriber_client.bal
> $subject
Related to HTTP PR [#998](https://github.com/ballerina-platform/module-ballerina-http/pull/998)
N/A
=> Remove `http:Payload` usage from WebSub module

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Update dependency versions

ballerina/tests/ballerina/tests/subscriber_with_opt_service_path_test.bal, ballerina/tests/test_init.bal, docs/spec/spec.md
> $subject
Related to [#2932](https://github.com/ballerina-platform/ballerina-standard-library/issues/2932)
N/A
=> Add test cases for service-path auto-gen disabled scenarios

build-config/resources/Ballerina.toml, gradle.properties
=> Update to stable lang version `2201.1.0`

gradle.properties
=> Update dependency versions related to `2201.0.4`

ballerina/Dependencies.toml, gradle.properties
=> Update to stable version before publishing to staging-central

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, build.gradle, gradle.properties
> $Subject
> Related to [`Add details for native jars used in the standard library #3117`](https://github.com/ballerina-platform/ballerina-standard-library/issues/3117)
N/A
=> Migrate to Ballerina Update 2

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
> $subject
Related to [#3315](https://github.com/ballerina-platform/ballerina-standard-library/issues/3315)
Part of [#3447](https://github.com/ballerina-platform/ballerina-standard-library/issues/3447)
N/A
=> Update dependency versions to support native-image build

ballerina-tests/Dependencies.toml, ballerina/subscriber_client.bal, ballerina/tests/utils_test.bal, changelog.md
> $subject
Fixes [#2941](https://github.com/ballerina-platform/ballerina-standard-library/issues/2941)
N/A
=> Update logic to encode subscription-request params properly

changelog.md, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websub/CompilerPluginTest.java, compiler-plugin-tests/src/test/resources/ballerina_sources/sample_24/Ballerina.toml, compiler-plugin-tests/src/test/resources/ballerina_sources/sample_24/service.bal, compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/AnalyserUtils.java, compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/ListenerInitAnalysisTask.java
> $subject
Part of [#2782](https://github.com/ballerina-platform/ballerina-standard-library/issues/2782)
N/A
=> [FIX] Compiler plugin validation logic for `websub:Listener` args when a `check` expression is present

.github/workflows/build-with-bal-test-native.yml, README.md, ballerina-tests/build.gradle, gradle.properties
> $subject
Part of [#3316](https://github.com/ballerina-platform/ballerina-standard-library/issues/3316)
N/A
=> Add Build with `bal test native` workflow

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties, native/src/main/java/io/ballerina/stdlib/websub/NativeHttpToWebsubAdaptor.java
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
=> Fix failing build for type reference support

docs/spec/spec.md
Fix HTTP listener config broken link
=> Fix HTTP listener config broken link

.github/workflows/pull-request.yml
> $Subject
Related to [#4098](https://github.com/ballerina-platform/ballerina-standard-library/issues/4098)
N/A
=> Add codecov token to pr build workflow and add workflow calls to load tests

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update dependency versions for 2201.5.0 release

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/build.gradle, ballerina/resource_discovery.bal, ballerina/tests/additional_external_error_data_test.bal, ballerina/utils.bal, build.gradle, gradle.properties
=> Replace ballerina/regex usage with ballerina-lang regex

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties
=> Update std lib versions

.github/workflows/build-with-bal-test-graalvm.yml, README.md, ballerina-tests/build.gradle, gradle.properties
> $subject
Part of: [#4548](https://github.com/ballerina-platform/ballerina-standard-library/issues/4548)
N/A
=> Incoperate native build command change

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/tests/subscription_initiation_test.bal, gradle.properties
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3961
=> Fix test failure due to error structure change in http

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, build-config/resources/BallerinaTest.toml, gradle.properties
Part of : [#4568](https://github.com/ballerina-platform/ballerina-standard-library/issues/4568)
N/A
=> Mark GraalVM compatibility

gradle.properties
=> Update HTTP dependency version

.github/workflows/build-timestamped-master.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml, .github/workflows/update_specs.yml, README.md, ballerina-tests/Ballerina.toml, ballerina/Ballerina.toml, build-config/checkstyle/build.gradle, build-config/resources/Ballerina.toml, build-config/resources/BallerinaTest.toml, build.gradle, compiler-plugin-tests/src/test/resources/ballerina_sources/sample_19/Ballerina.toml, gradle.properties, gradle/wrapper/gradle-wrapper.properties, native/build.gradle, settings.gradle, spotbugs-exclude.xml
=> Migrate to Java 17

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Bump to the Next Minor Version and Update the Distribution

.github/workflows/central-publish.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml
=> Update java-version to 17.0.7

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/annotation.bal, ballerina/commons.bal, ballerina/subscriber_client.bal, ballerina/tests/subscription_initiation_test.bal, ballerina/utils.bal, changelog.md, docs/spec/spec.md
> $subject
Fixes: [#4795](https://github.com/ballerina-platform/ballerina-standard-library/issues/4795)
N/A
=> Add support to send custom parameters/headers in the subscription request

changelog.md
=> Update change log after `2.9.1` release

ballerina/annotation.bal, ballerina/commons.bal, ballerina/subscriber_client.bal, ballerina/tests/subscription_initiation_test.bal, ballerina/utils.bal, changelog.md, docs/spec/spec.md
> $subject
Related to: [#4795](https://github.com/ballerina-platform/ballerina-standard-library/issues/4795)
N/A
=> [Master] Add support to send custom parameters/headers in the subscription request

ballerina/annotation.bal, docs/spec/spec.md
=> Fix grammar issues

ballerina/annotation.bal, docs/spec/spec.md
=> [Master] Fix grammar issues

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, changelog.md, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websub/TestUtils.java, compiler-plugin/src/main/java/io/ballerina/stdlib/websub/CommonUtil.java, compiler-plugin/src/main/java/io/ballerina/stdlib/websub/action/CodeActionUtil.java, compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/AnalyserUtils.java, native/src/main/java/io/ballerina/stdlib/websub/NativeHttpToWebsubAdaptor.java, native/src/main/java/io/ballerina/stdlib/websub/NativeWebSubListenerAdaptor.java
Closes ballerina-platform/ballerina-standard-library#4927.
=> Make some of the Java classes proper utilities

.github/workflows/build-timestamped-master.yml, .github/workflows/build-with-bal-test-graalvm.yml, .github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, .github/workflows/trivy-scan.yml
=> Update workflow template links

native/src/main/java/io/ballerina/stdlib/websub/NativeHttpToWebsubAdaptor.java
=> Update callMethod logic for Java 21

ballerina/request_processor.bal, ballerina/tests/basic_subscriber_test.bal, changelog.md
> $subject
Fixes: [#7666](https://github.com/ballerina-platform/ballerina-library/issues/7666)
N/A
=> [2201.11.x] Fix content-type resolution in the received HTTP request

ballerina-tests/Ballerina.toml, ballerina-tests/Dependencies.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
This PR contains automated changes for update 12 release.
=> [Automated] Prepare for Update 12 release
