.github/workflows/build-master.yml
.github/workflows/daily-build.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
websub-ballerina/build.gradle

$subject
- Add ballerina central access token to provide the functionality to make independent releases. So, developers can make independent releases, and those releases publish artifacts to GitHub packages and also push to ballerina central.
- Sometimes releases fail due to unexpected problems in the containerized environments(Jenkins). At that time we may need to skip the ballerina releases. To do that we introduce a Gradle parameter. When you enable `-PskipBallerinaTests=true`, you can build without skipping the ballerina test cases. For example:
```sh
./gradlew clean build -PskipBallerinaTests=true
```

Improve build scripts to release independently

---

websub-ballerina/src/websub/commons.bal
websub-ballerina/src/websub/hub_configuration.bal
websub-ballerina/src/websub/hub_persistence.bal
websub-ballerina/src/websub/hub_service.bal
websub-ballerina/src/websub/natives.bal
websub-ballerina/src/websub/publisher_client.bal
websub-ballerina/src/websub/subscriber_client.bal
websub-ballerina/src/websub/subscriber_service_caller.bal
websub-ballerina/src/websub/subscriber_service_endpoint.bal
websub-native/build.gradle

$subject
**Approach**
- The Ballerina hub related APIs can be mark as isolated since we are using a static hub.
- As we did in socket and HTTP, here the publisher and subscriber APIs can be isolated since those work independently without accessing any shared resources.
- Fix Stdlib native JAR resolution
- macOS
- Java 8
- SLP4

Enable isolation support and fix native JAR resolution

---

websub-ballerina/annotation.bal
websub-ballerina/commons.bal
websub-ballerina/subscriber_service_endpoint.bal
websub-generic-integration-tests/tests/constants.bal
websub-generic-integration-tests/tests/test_content_negotiation.bal
websub-native/src/main/java/org/ballerinalang/net/websub/WebSubSubscriberConstants.java
websub-native/src/main/java/org/ballerinalang/net/websub/nativeimpl/SubscriberNativeOperationHandler.java

Add accept and acceptLanguage fields to SubscriberServiceConfig annotation for content negotiation in the initial discovery request.
Use annotation to retrieve accept and acceptLanguage fields.
Add retrieved values to initial discovery request.
```ballerina
@websub:SubscriberServiceConfig {
path: "/ordereventsubscriber",
subscribeOnStartUp: true,
target: "http://localhost:9091/ordermgt/order",
accept:"application/json",
acceptLanguage:"de-DE",
leaseSeconds: 3600,
secret: "Kslk30SNF2AChs2"
}
```

Add content negotiation

---

websub-ballerina/build.gradle

> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476

Change ballerina archive extension to bala

---

websub-ballerina/sub_listener.bal
websub-ballerina/tests/websub_config_manual_attach_test.bal

With this change developers could initialize a `websub:SubscriberService` with custom configurations and attach it to `websub:Listener`.
Developer should be able to implement a webhook-service library using `websub:SubscriberService`. When implementing a library developer should be able to pass custom configuration values to underlying `websub:SubscriberService`. But in current implementation `websub:SubscriberService` only support annotation based configurations and hence we could not pass dynamic configuration values to underlying `websub:SubscriberService`. 
```ballerina
import ballerina/websub;
import ballerina/log;
service class SimpleWebsubService {
*websub:SubscriberService;
remote function onSubscriptionValidationDenied(websub:SubscriptionDeniedError msg) 
returns …
```

Add public method to initialize a subscriber-service with custom configuration

---

websub-ballerina/commons.bal
websub-ballerina/request_processor.bal
websub-ballerina/tests/basic_subscriber_test.bal
websub-ballerina/tests/content_verification_test.bal
websub-ballerina/tests/multi_service_listener_test.bal
websub-ballerina/tests/ssl_enabled_subscriber_test.bal
websub-ballerina/tests/websub_config_manual_attach_test.bal
websub-ballerina/utils.bal

> $subject
> Updated `x-form-urlencoded` support for content distribution.
```ballerina
@websub:SubscriberServiceConfig {
target: ["https://sample.hub", "https://sample.topic.two"], 
leaseSeconds: 36000,
secret: "secretKey"
} 
service /subscriber on new websub:Listener(9090) {
remote function onEventNotification(websub:ContentDistributionMessage event) 
returns websub:Acknowledgement|websub:SubscriptionDeletedError? {
match event.contentType {
mime:APPLICATION_FORM_URLENCODED => {
map<string|string[]> content = <map<string|string[]>> event.content;
// implement the event notification logic for x-form-urlencoded content
}
_ => {
// implement the event notification logic for other content types
}
}
return websub:ACKNOWLEDGEMENT;
}
}
```
> #159 
Fixes: …

Fix issue in url-encoded content retrieval

---

websub-ballerina/resource_discovery.bal
websub-ballerina/subscriber_client.bal
websub-ballerina/tests/additional_external_error_data_test.bal
websub-ballerina/tests/basic_subscriber_test.bal
websub-ballerina/tests/multi_service_listener_test.bal
websub-ballerina/tests/ssl_enabled_subscriber_test.bal
websub-ballerina/tests/subscriber_with_error_return_types.bal
websub-ballerina/tests/websub_config_manual_attach_test.bal

> $subject
This reverts [b91f5c9](https://github.com/ballerina-platform/module-ballerina-websub/pull/263/commits/b91f5c96713568946a88959d9c734ccbdd4854c3)
Related to [#425](https://github.com/ballerina-platform/module-ballerina-http/pull/425)

Revert "Sync with HTTP inbound error response update"

---

gradle.properties

> Netty : 4.1.65.Final
> TCNative: 2.0.39.Final
Related to [#1446](https://github.com/ballerina-platform/ballerina-standard-library/issues/1446)

Upgrade Netty and TCNative Version

---

changelog.md
websub-ballerina/native.bal
websub-ballerina/request_processor.bal
websub-ballerina/tests/utils_test.bal
websub-ballerina/utils.bal
websub-native/src/main/java/io/ballerina/stdlib/websub/Constants.java
websub-native/src/main/java/io/ballerina/stdlib/websub/NativeHttpToWebsubAdaptor.java

> $subject
Fixes [#1484](https://github.com/ballerina-platform/ballerina-standard-library/issues/1484)
To retrieve only the first header value: 
```ballerina
@websub:SubscriberServiceConfig{
// add the required configuration
}
service /subscriber on new Listener(9101) {
isolated remote function onEventNotification(websub:ContentDistributionMessage event) returns websub:Acknowledgement {
string|http:HeaderNotFoundError headerValue = getHeader(event, "Custom-Header");
// implement the logic here
}
}
```
To retrieve all the header values to which the specified header key maps to:
```ballerina
@websub:SubscriberServiceConfig{
// add the required configuration
}
service /subscriber on new Listener(9101) {
isolated remote function onEventNotification(websub:ContentDistributionMessage event) …
```

Util method to retrieve http-headers from content-distribution message

---

.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/trivy-scan.yml
README.md

This PR integrates the [Trivy](https://github.com/aquasecurity/trivy) vulnerability scanner for the repository file system and it will check and generate the report daily or on-demand and before the release.
Related Issue: [#1849](https://github.com/ballerina-platform/ballerina-standard-library/issues/1849)

Add trivy scan for release builds and add daily trivy scan build

---

ballerina/Module.md

> $subject
Fixes [#1904](https://github.com/ballerina-platform/ballerina-standard-library/issues/1904)

[FIX] The spelling of ngrok is incorrect in websub API docs

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/http_service.bal
ballerina/tests/unsubscription_test.bal
changelog.md

> $subject
Fixed [#2448](https://github.com/ballerina-platform/ballerina-standard-library/issues/2448)
If the developer has not implemented the `onSubscriptionDenied` method as in following sample:
```ballerina
@websub:SubscriberServiceConfig { 
target: ["https://sample.hub.com", "https://sample.topic.com"],
} 
service on securedSubscriber {
remote function onEventNotification(websub:ContentDistributionMessage event) returns websub:Acknowledgement{
log:printInfo("onEventNotification invoked ", contentDistributionMessage = event);
return websub:ACKNOWLEDGEMENT;
}
}
```
There will be a log line printed if the subscription request is denied by the hub:
```sh
ERROR module = ballerina/websub message = "Subscription is denied by the hub"
```

Notify user of Subscription denial from the `hub` when `onSubscriptionDenied` is not implemented

---

ballerina/tests/subscriber_with_readonly_method_params_test.bal
changelog.md
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websub/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/ballerina_sources/sample_23/Ballerina.toml
compiler-plugin-tests/src/test/resources/ballerina_sources/sample_23/service.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/AnalyserUtils.java
native/src/main/java/io/ballerina/stdlib/websub/Constants.java
native/src/main/java/io/ballerina/stdlib/websub/NativeHttpToWebsubAdaptor.java

> $subject
Related to [#2604](https://github.com/ballerina-platform/ballerina-standard-library/issues/2604)
With this change developers could use `reaonly` parameters for remote methods in `websub:SubscriberService`:
```ballerina
@SubscriberServiceConfig {
target: "https://discover.hub/discovery",
leaseSeconds: 36000
}
service /subscriber on subListener {
isolated remote function onSubscriptionValidationDenied(readonly & websub:SubscriptionDeniedError msg) returns websub:Acknowledgement? {
// implement logic here
return websub:ACKNOWLEDGEMENT;
}
remote function onUnsubscriptionVerification(readonly & websub:UnsubscriptionVerification msg)
returns websub:UnsubscriptionVerificationSuccess|websub:UnsubscriptionVerificationError {
if (msg.hubTopic == "test1") {
return …
```

`readonly` support for the parameters of remote methods

---

ballerina-tests/tests/service_path_generation_disabled_test.bal
ballerina-tests/tests/service_path_generation_test.bal
ballerina/commons.bal
ballerina/sub_listener.bal
ballerina/tests/utils_test.bal
changelog.md
docs/spec/spec.md

> $subject
Fixes [#2932](https://github.com/ballerina-platform/ballerina-standard-library/issues/2932)
With this fix following code-segment should work properly:
```ballerina
import ballerina/log;
import ballerina/websub;
@websub:SubscriberServiceConfig {
target: ["https://sample.hub.com", "https://sample.topic.com"],
callback: "https://sample.subscriber.com"
}
service on new websub:Listener(9091) {
remote function onEventNotification(readonly & websub:ContentDistributionMessage msg) returns websub:Acknowledgement {
log:printInfo("Received content update: ", payload = msg);
return websub:ACKNOWLEDGEMENT;
}
}
```

Allow running `websub:SubscriberService` by providing the callback URL without providing the service-path

---

ballerina-tests/Dependencies.toml
ballerina-tests/tests/service_path_generation_test.bal
ballerina/sub_listener.bal
ballerina/tests/utils_test.bal
changelog.md

When attaching a WebSub subscriber-service to a WebSub listener if the attach-point is provided as `/` the subscriber-service initiation failed with a panic. The issue for this is when a service is attached to `/` path ballerina-runtime will assign an empty array to denote the service-path, which in current logic determines as an empty service-path and try to retrieve the auto-generated  service-path which is not available. 
Ballerina runtime behavior is clarified in ballerina-lang issue [#29960](https://github.com/ballerina-platform/ballerina-lang/issues/29960) and ballerina-spec issue [#810](https://github.com/ballerina-platform/ballerina-spec/issues/810). 
So, updated the logic that if the service-path provided to the listener attach method is an empty array, then to consider that …

[FIX] WebSub subscriber service results in panic with service path not found

---

ballerina/annotation.bal
ballerina/subscriber_client.bal
ballerina/tests/subscription_initiation_test.bal
docs/spec/spec.md

> $subject
Part of: [#4795](https://github.com/ballerina-platform/ballerina-standard-library/issues/4795)
N/A

Add custom headers and parameters to the unsubscription request

---

ballerina/annotation.bal
ballerina/subscriber_client.bal
ballerina/tests/subscription_initiation_test.bal
docs/spec/spec.md

> $subject
Part of: [#4795](https://github.com/ballerina-platform/ballerina-standard-library/issues/4795)
N/A

[Master] Add custom headers and parameters to the unsubscription request

---

ballerina/tests/subscription_initiation_test.bal

This is to fix the test case with the error message change done in the `http` module via this [PR](https://github.com/ballerina-platform/module-ballerina-http/pull/1846).
N/A

Fix error message assertion

---

ballerina-tests/Dependencies.toml
ballerina/Dependencies.toml
changelog.md
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/websub/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/ballerina_sources/sample_25/Ballerina.toml
compiler-plugin-tests/src/test/resources/ballerina_sources/sample_25/service.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/websub/task/ListenerInitAnalysisTask.java

> $subject
Part of: [#6339](https://github.com/ballerina-platform/ballerina-library/issues/6339)
Allow following listener declaration:
```ballerina
int port = 9000;
listener websub:Listener ln = new(port, host = os:getEnv("HOSTNAME"));
```

Fix compiler plugin validation not allowing listener port to be a pre-defined variable

---

ballerina-tests/Dependencies.toml
ballerina/Dependencies.toml
gradle.properties
gradle/wrapper/gradle-wrapper.properties

Update versions for U11

---

ballerina/request_processor.bal
ballerina/tests/basic_subscriber_test.bal
changelog.md

> $subject
Fixes: [#7666](https://github.com/ballerina-platform/ballerina-library/issues/7666)
N/A

Fix content-type resolution in the received HTTP request
